const dummyChatData=[
    {id:1,message:"Hello",timeAt:"12:05",user:"chirag"},
    {id:2,message:"hyy",timeAt:"12:05",user:"rohit"},
    {id:3,message:"How are you",timeAt:"12:05",user:"chirag"},
    {id:4,message:"fine ,u?",timeAt:"12:06",user:"rohit"},
//     {id:5,message:"me also fine",timeAt:"12:06",user:"chirag"},
//     {id:6,message:"so what prgress in project..",timeAt:"12:06",user:"chirag"},
//     {id:7,message:"its going good",timeAt:"12:06",user:"rohit"},
//     {id:8,message:"nice nice",timeAt:"12:06",user:"chirag"},
//     {id:9,message:"yes",timeAt:"12:07",user:"rohit"},
//     {id:10,message:"and what about that thing",timeAt:"12:07",user:"chirag"},
//     {id:11,message:"which ??",timeAt:"12:07",user:"rohit"},
//     {id:12,message:"you don't know?",timeAt:"12:07",user:"chirag"},
//     {id:13,message:"No.",timeAt:"12:08",user:"rohit"},
//     {id:14,message:"ahh sorry,i think i forgot",timeAt:"12:08",user:"chirag"},
//     {id:15,message:"no issue",timeAt:"12:08",user:"rohit"},
//     {id:16,message:"yes ",timeAt:"12:08",user:"chirag"},
//     {id:17,message:"now tell me then",timeAt:"12:08",user:"rohit"},
//     {id:18,message:"yea sure",timeAt:"12:08",user:"chirag"},
//     {id:19,message:"hmm",timeAt:"12:09",user:"rohit"},
//     {id:20,message:"i am talking about an ampify course",timeAt:"12:09",user:"chirag"},
//     {id:21,message:"okkk",timeAt:"12:09",user:"rohit"},
//     {id:22,message:"yes",timeAt:"12:09",user:"chirag"},
//     {id:23,message:"you can also see that its so much goog",timeAt:"12:10",user:"chirag"},
//     {id:24,message:"ok then share me credentials",timeAt:"12:10",user:"rohit"},
//     {id:25,message:"yea sure",timeAt:"12:10",user:"chirag"},
//     {id:26,message:"thanks i'll see",timeAt:"12:10",user:"rohit"},
//     {id:27,message:"yes",timeAt:"12:10",user:"chirag"},
//     {id:28,message:"hmm.",timeAt:"12:11",user:"rohit"},
//     {id:29,message:"and lets close now i think",timeAt:"12:11",user:"chirag"},
//     {id:30,message:"yea sure ",timeAt:"12:11",user:"rohit"},
//     {id:31,message:"ok then",timeAt:"12:11",user:"chirag"},
//     {id:32,message:"byy",timeAt:"12:11",user:"chirag"},
//     {id:33,message:"byyy",timeAt:"12:11",user:"rohit"},
]
export default dummyChatData;